from tests.CardBaseTestDir.DrunkTests import DrunkTests
from tests.CardBaseTestDir.HunterTests import HunterTests
from tests.CardBaseTestDir.InsomniacTests import InsomniacTests
from tests.CardBaseTestDir.MasonTests import MasonTests
from tests.CardBaseTestDir.MinionTests import MinionTests
from tests.CardBaseTestDir.RobberTests import RobberTests
from tests.CardBaseTestDir.SeerTests import SeerTests
from tests.CardBaseTestDir.TannerTests import TannerTests
from tests.CardBaseTestDir.TroublemakerTests import TroublemakerTests
from tests.CardBaseTestDir.VillagerTests import VillagerTests
from tests.CardBaseTestDir.WerewolfTests import WerewolfTests
