from tests.CardDaybreakTestDir.AlphaWolfTests import AlphaWolfTests
from tests.CardDaybreakTestDir.ApprenticeSeerTests import ApprenticeSeerTests
from tests.CardDaybreakTestDir.DreamWolfTests import DreamWolfTests
from tests.CardDaybreakTestDir.MysticWolfTests import MysticWolfTests
from tests.CardDaybreakTestDir.VillageIdiotTests import VillageIdiotTests
